name: asciiview
version: 'git'
summary: Convert images into ASCII in your terminal
description: |
  It turns images into an ASCII art representation based on the shape of the characters
  
    **Install the snap**

    sudo snap install asciiview
    
    **Run it**
    
    asciiview
    
    Use asciiview --help for usage info

base: core18
grade: stable 
confinement: strict

apps:
  asciiview:
    command: python3 $SNAP/asciiview.py
    environment:
      LC_ALL: C.UTF-8
    plugs:
      - home
      
parts: 
  asciiview:
    source: https://github.com/kz6fittycent/asciiview
    source-type: git
    plugin: nil
      
    build-packages:
      - python3

    stage-packages:
      - python3
      - python3-pil
      - python3-numpy  
          
  publish:
    plugin: dump
    source: .      
